### ISSUE TITLE
[high priority] esprima-fb can't handle RegExp properly

### ISSUE THREAD

**Issue by millermedeiros** [millermedeiros/rocambole#20]
I believe it adds the wrong `range` info.. will need to investigate it before a release.

**Comment by royriojas** [comment]
To add more info to this issue, here is a bug report on the esprima-fb fork (the issue seems to be in the esprima harmony branch actually.

https://github.com/facebook/esprima/issues/74

**Comment by millermedeiros** [comment]
I think I'll just use `esprima@2.0` for now since it introduced just a simple regression on esformatter and it does support ES6 features.
