### ISSUE TITLE
Does rocambole support source maps?

### ISSUE THREAD

**Issue by jantimon** [millermedeiros/rocambole#21]
I would like to alter javascript code to fix [an IE8 issue](http://stackoverflow.com/questions/24784222/preprocessor-to-replace-javascript-keywords?noredirect=1#comment38466401_24784222).

Is it possible to pass a source map in, alter the javascript code and update both the source map and the javascript code?

**Comment by millermedeiros** [comment]
@jantimon sorry for the huge delay, I have no plans to support source maps. you would need to update the javascript code and generate a new source map afterwards.
