### ISSUE TITLE
security issue in test files

### ISSUE THREAD

**Issue by papakai** [millermedeiros/rocambole#31]
fyi: retire.js detected this:

node_modules/rocambole/test/files/jquery.js
 ↳ jquery 1.8.3 has known vulnerabilities: severity: medium; bug: 11290, summary: Selector interpreted as HTML; http://bugs.jquery.com/ticket/11290 http://research.insecurelabs.org/jquery/test/ severity: medium; issue: 2432, summary: 3rd party CORS request may execute; https://github.com/jquery/jquery/issues/2432 http://blog.jquery.com/2016/01/08/jquery-2-2-and-1-12-released/

**Comment by SethDavenport** [comment]
Is it necessary to ship the `test` folder as part of npm?  Because if not, you could consider adding a `.npmignore` to address this.

**Comment by SethDavenport** [comment]
Let me know if that makes sense and I can make a PR.

**Comment by millermedeiros** [comment]
will add the test files to `.npmignore` today! all my notifications were muted on github and I only saw it now 🤦‍♂️
