### ISSUE TITLE
Ecma7 Support

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [millermedeiros/rocambole#32]
Is it possible to have async/await support?

**Comment by ZatsuneNoMokou** [comment]
`esprima`  need to by updated to version 4.0.0, `npm test` pass with it.

**Comment by jonnymanok** [comment]
Esprima have flaws in it's async/await implementation, and the specs have changed since Esprima implemented it. Acorn is up to date when it comes to ES6 support. Cherow support latest features.
